# Generated by Django 4.0.2 on 2022-04-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('checkbox', models.CharField(default='', max_length=255)),
                ('duedate', models.DateTimeField(default='2022-04-21 22:28:47')),
                ('created_at', models.DateTimeField(default='2022-04-21 22:28:47')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskapp.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='involved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Involved', to='taskapp.user'),
        ),
    ]
