# Generated by Django 4.0.2 on 2022-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkbox',
            field=models.CharField(default='', max_length=255),
        ),
    ]
