# Generated by Django 4.0.2 on 2022-04-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_task_created_at_alter_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default='2022-04-21 22:41:01'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(default='2022-04-21 22:41:01'),
        ),
        migrations.AlterField(
            model_name='task',
            name='involved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Involved', to='taskapp.user'),
        ),
    ]
