# Generated by Django 4.0.2 on 2022-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_task_created_at_alter_task_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default='2022-05-05 13:18:45'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(default='2022-05-05 13:18:45'),
        ),
    ]
